server:
  port:8111
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.3:9092
      bindings:
        sensor-in:
          destination: sensor
        sensor-out:
          destination: sensor
